name: Build 1

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        uses: waruhachi/theos-action@v1
        with:
          theos-src: theos/theos
          theos-branch: main
          sdks-src: theos/sdks
          sdks-branch: master

      - name: Build roothide package
        run: |
          make clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: 1-roothide-deb
          path: packages/*.deb