name: Build SimpleCowbell

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git "$HOME/theos"

      - name: Install SDK
        run: |
          git clone https://github.com/theos/sdks.git "$HOME/sdks"
          mkdir -p "$HOME/theos/sdks"
          cp -R "$HOME/sdks/iPhoneOS16.5.sdk" "$HOME/theos/sdks/"

      - name: Install ldid
        run: |
          brew update
          brew install ldid

      - name: Build
        run: |
          export THEOS="$HOME/theos"
          export PATH="/opt/homebrew/bin:$PATH"

          which ldid
          ldid -h

          make clean
          make package FINALPACKAGE=1

      - name: List packages
        run: |
          ls -lah packages/

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: SimpleCowbell-deb
          path: packages/*.deb